### ISSUE TITLE
SUB:* segfaults

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/cg3#19]
See attached test data and test cg file. Leaving out the `SUB` keyword makes everything work fine, and also `SUB:1` works fine. It is specifically `SUB:*` that crashes `vislcg3`:

```
$ vislcg3 -g valency.cg3 < test.txt 
Segmentation fault: 11
```

[Arkiv.zip](https://github.com/TinoDidriksen/cg3/files/2479508/Arkiv.zip)

```
$ vislcg3 --version
VISL CG-3 Disambiguator version 1.1.7.13204
Copyright (C) 2007-2018 GrammarSoft ApS. Licensed under GPLv3+
```

macOS 10.13.6

**Comment by TinoDidriksen** [comment]
`SUB:*` is not valid for reading-manipulating rule types, because it creates a magic combined reading of all sub-readings. But obviously this should show a nicer error message, or be made to work as expected.
