### ISSUE TITLE
cg-mwesplit reports wrong line number

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/cg3#22]
When running the attached text through cg-mwesplit, it reports the following error:

```
WARNING: Line 65: Some but not all main-readings of "<geassem.>" had wordform-tags (not completely mwe-disambiguated?), not splitting.
```

But as can be seen in the file, the offending cohort start on line 31, and ends on line 43. This misreporting of line numbers can be annoying when trying to debug disambiguation errors in large files.

[test1.txt](https://github.com/TinoDidriksen/cg3/files/2584435/test1.txt)

**Comment by unhammer** [comment]
@TinoDidriksen can we store the line number of a cohort in the `Cohort` class? Otherwise I think I'd have to duplicate all of `runGrammarOnText` :-S

**Comment by TinoDidriksen** [comment]
Sure. I've considered doing that, but so far just wrote messages as "something happened before input line N".

**Comment by TinoDidriksen** [comment]
`uint32_t line_number = 0;` to avoid needing init in the constructor, but otherwise looks fine.

**Comment by unhammer** [comment]
committed as r13318
