### ISSUE TITLE
new release tag request for icu4c 59.1 compatibility

### ISSUE THREAD

**Issue by ilovezfs** [TinoDidriksen/cg3#3]
Do you mind creating a new release tag here on GitHub and/or a new tarball for http://beta.visl.sdu.dk/download/vislcg3/ ? We need the fixes from HEAD in Homebrew since icu4c in Homebrew has been upgraded to 59.1, which breaks `cg3-1.0.0~r12200` (and `cg3-0.9.9~r10800`).

Cf. https://github.com/Homebrew/homebrew-science/pull/6165

**Comment by TinoDidriksen** [comment]
Done. See https://visl.sdu.dk/download/vislcg3/ or https://github.com/TinoDidriksen/cg3/releases/tag/v1.1.0

**Comment by ilovezfs** [comment]
Thanks!
