### ISSUE TITLE
How to make a set match within all subreadings of One reading?

### ISSUE THREAD

**Issue by unhammer** [TinoDidriksen/cg3#38]
Is there a way to pretend subreadings of a reading are flattened into one reading?

Say we had an modifier `/_`, then `(NOT 0/_ (*) - (Err))` would be true for
```
	"a" N Cmp
		"b" N Cmp Err
```
and false for
```
	"a" N
		"b" N Cmp Err
	"a" N
		"b" N Cmp
```

just like `(NOT 0 (*) - (Err))` is true for
```
	"a" N Cmp "b" N Cmp Err
```
and false for
```
	"a" N "b" N Cmp Err
	"a" N "b" N Cmp
```

**Comment by TinoDidriksen** [comment]
That is what `/*` does. https://visl.sdu.dk/cg3/chunked/subreadings.html

> If N is * then the test will search the main reading and all sub-readings.

**Comment by unhammer** [comment]
Ooh, I've been thinking it checked all subreadings as separate readings, but that's great. So for future reference, here are some ways to check possible combinations:

input:
```
"<AllErrors>"
	"a" N Cmp
		"b" N Cmp Err
	"a" N Cmp Err
		"b" N Cmp
: 
"<Ambig>"
	"a" N
		"b" N Cmp Err
	"a" N
		"c" N Cmp
: 
"<NoErrors>"
	"a" N
		"b" N Cmp
	"a" N
		"c" N Cmp
```

grammar:
```
SET Err = (Err) ;
SET NotErr = (*) - (Err) ;

ADD (&AllErrors) (*) IF (NOT 0/* NotErr) ;

ADD (&Ambig) (*)     IF (0/* Err)     (0/* NotErr) ;

ADD (&NoErrors) (*)  IF (NOT 0/* Err) (0/* NotErr) ;
```

output:
```
"<AllErrors>"
	"a" N Cmp &AllErrors ADD:4
		"b" N Cmp Err
	"a" N Cmp Err &AllErrors ADD:4
		"b" N Cmp
: 
"<Ambig>"
	"a" N &Ambig ADD:6
		"b" N Cmp Err
	"a" N &Ambig ADD:6
		"c" N Cmp
: 
"<NoErrors>"
	"a" N &NoErrors ADD:8
		"b" N Cmp
	"a" N &NoErrors ADD:8
		"c" N Cmp
```
