### ISSUE TITLE
A way to query other readings of the target

### ISSUE THREAD

**Issue by TinoDidriksen** [TinoDidriksen/cg3#62]
`0` queries all readings of a cohort, but sometimes we only want to look at the other readings of the target cohort. Need some way to refer to readings not currently being considered by the active rule.

Should also work with `C` so that `other` is any other reading, but `other+C` is all other readings.

**Comment by lynnda-hill** [comment]
The type of rule I have been thinking of is the following:

REMOVE Adv IF  "all the other line in the target include Err/Orth"

So if there is any reading than the Adv reading that does not include Err/Orth, the rule should apply. If all the other lines include Err/Orth, the rule should not apply.

**Comment by TinoDidriksen** [comment]
This is done and deployed, btw. Modifier `t` will look at non-target readings, https://visl.sdu.dk/cg3/chunked/contexts.html#test-other
